modName = XT9Y Features
modId = xt9yfeatures
modGroup = com.xt9y.features
useModGroupForPublishing = false

autoUpdateBuildScript = false

minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Developer

enableModernJavaSyntax = jvmDowngrader
downgradeTargetVersion = 8
jvmDowngraderMultiReleaseVersions = 17,21,25
jvmDowngraderStubsProvider = gtnhlib
enableGenericInjection = true

generateGradleTokenClass = com.xt9y.features.Tags
gradleTokenVersion = VERSION

apiPackage =

usesMixins = true
separateMixinSourceSet = mixin
usesMixinDebug = true
mixinPlugin =
mixinsPackage = mixin.mixins
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = true

usesShadowedDependencies = false
minimizeShadowedDependencies = false
relocateShadowedDependencies = false

includeWellKnownRepositories = true

usesMavenPublishing = false
modrinthProjectId =
curseForgeProjectId =

org.gradle.configuration-cache = true
org.gradle.jvmargs = -Xmx2g
org.gradle.parallel = true
